puts "Enter your phone number :"
number = gets.chomp 


100.times do
 puts "connecting .......
 connecting .....
 connecting ....
 connecting .......
 connecting .....
 connecting ....
 connecting .......
 connecting .....
 connecting ...
 .connecting .......
 connecting .....
 connecting ....
 "
 
end

puts "trying to connect ...........#{number}"
puts 
puts
puts "successfully connected to the #{number}"